services:
  app:
    image: ${ORGNAME}/${SERVICENAME}
    restart: unless-stopped
    container_name: ${SERVICENAME}
    volumes:
      - "./config.yml:/usr/src/app/config.yml"
    environment:
      - LDAP_BIND_PASSWORD
    depends_on:
      - redis
    networks:
      - default
      - ldap

  redis:
    image: redis:alpine
    container_name: ${SERVICENAME}-redis
    restart: unless-stopped
    volumes:
      - "${VOLUMES_DIR}/redis:/data"

networks:
  ldap:
    name: ldap
    external: true
